#!/usr/bin/env python3

# gaia-stardb: Processing Gaia DR2 for celestia.Sci/Celestia
# Copyright (C) 2019–2021  Andrew Tribick
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

"""Entry point for downloading the data files."""

from celestia_gaia.download_data import download_vizier, download_sao_xmatch
from celestia_gaia.gaia_data import (
    build_xmatches, download_gaia, download_gaia_distances,
)
from celestia_gaia.hip_dist import download_dist_prior, build_hip2_distances

download_vizier()
download_dist_prior()
build_hip2_distances()
download_sao_xmatch()
download_gaia()
build_xmatches()
download_gaia_distances()
